name: IPN
favicon: null
layout_spectrum: 1
typography_spectrum: 0.99986
title: IPN Ignite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#328a34'
    - '#fdb016'
    - '#015595'
    - '#a7c9e8'
  brandStrength: 0.5674553164280951
  lightness: 0.07243411289528012
  saturation: 0.1316217251587659
  rhythmicContrast: 0.8951458907686174
purpose: []
